# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=52, verbose_name='Service')),
                ('version', models.CharField(max_length=12, verbose_name='Version')),
                ('archeive', models.BooleanField(default=False, verbose_name='Archeive service')),
                ('change', models.CharField(choices=[('created', 'created'), ('changed', 'changed'), ('removed', 'removed')], default='created', max_length=12, verbose_name='Chioce')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Update date')),
            ],
        ),
    ]
